services:
  - type: web
    name: neva-pro-backend
    env: node
    rootDir: N.E.V.A Pro/backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /docs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
